### ISSUE TITLE
sudo --stdin does not seem to work

### ISSUE THREAD

**Issue by sebthom** [chrisant996/sudo-windows#1]
I am trying to perform an non-interactive command execution with sudo in a batch file.

I tried the following ways but always receive `The user name or password is incorrect.`
```batch
C:\> echo thePassword | sudo -S -u theUser whoami
Enter password for theUser:
The user name or password is incorrect.
sudo failed.

C:\> echo | set /p=thePassword | sudo -S -u theUser whoami
Enter password for theUser:
The user name or password is incorrect.
sudo failed.

C:\> echo | set /p dummyName=thePassword | sudo -S -u theUser whoami
Enter password for theUser:
The user name or password is incorrect.
sudo failed.
```

any ideas?

**Comment by chrisant996** [comment]
Two problems:
1. `echo thePassword |` there is a space between the password and the pipe character, and the space becomes part of the password.
2. It's not able to read the password from stdin properly. I forgot to use ReadFile() instead of ReadConsoleW() when reading directly from stdin.

Also, embedding secrets in scripts is highly insecure. I would encourage to not use an approach like that. I almost didn't even include `--stdin` at all for that reason (and I'm kind of glad I had a typo so that it doesn't work at the moment).

Anyway, this was mostly a project for me to explore how to elevate a process and attach it to the original non-elevated console window.  Consider using [gsudo](https://github.com/gerardog/gsudo) instead.  But gsudo does not allow reading a password from stdin (in fact it crashes if it's attempted).  Honestly, I only added `--stdin` here because the *nix version has it, but I'm absolutely shocked that it has it at all, because it's such a common and significant security vulnerability.

**Comment by chrisant996** [comment]
I don't plan to address this in the near future.

**Comment by chrisant996** [comment]
In fact, I will probably just remove `--stdin` altogether, because of the encoding challenges it creates.  I.e. what code page is stdin in...?  It's ambiguous, but it profoundly affects the ability to accurately read a password that contains non-ASCII characters.

**Comment by sebthom** [comment]
Hm a pity, I was trying to use the command in a github action to simulate execution of a batch file as another user. Your sudo command looked perfect. 

Would it be easier to read the PW from a file?

**Comment by chrisant996** [comment]
I'm a little surprised that the computer running the github action lets you create super user accounts on it, and lets you run arbitrary code as super user on the github action computer.  But I guess you must've found a way to do those.

_EDIT:  Oh, or maybe you just want to use "Super User Do" to run a program as a different user but not a super user; I'm still surprised it's letting you create accounts on the computer._

Reading a password from a file is even worse from a security perspective.

You'd need to use github's support for securely storing secrets in the repo settings, and have the github action insert the secret at execution time.

**Comment by sebthom** [comment]
Actions on a GitHub Actions Windows runner are executed with admin permissions. On Linux Runners it is a non-admin user but you have sudo permission.

Yes, what I wanted to achieve was execute a command as a nonadmin user while being logged in as an admin user.
Thanks to your last release, I am now successfully using your sudo command.
